version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fastapi_celery_example_web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env/.dev-sample
    # depends_on:
    #   - redis
      # - db


  rabbitmq:
    image: rabbitmq
    ports: 
      - 5672:5672


  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - rabbitmq
    #   - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: mher/flower:0.9.5
    command: /start-flower
    volumes:
      - .:/app
    environment: 
        - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
        - FLOWER_PORT=5555
    ports: 
        - 5555:5555
    depends_on: 
        - rabbitmq
      # - db

volumes:
  postgres_data: