apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-backend
  labels:
    k8s-app: scheduler-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: scheduler-backend
  template:
    metadata:
      labels:
        k8s-app: scheduler-backend
    spec:
      containers:
        - image: registry.digitalocean.com/edvora-test-registry/scheduler-api-default:9fd6be726ebc47ad417f09ab5e07724fffb3dca7
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 50Mi
