name: Deployment Pipeline

on:
  push:
    branches: [master]

env:
  DOCKER_IMAGE: registry.digitalocean.com/edvora-test-registry/scheduler-api-default:${{ github.sha }}

jobs:
  build:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Update manifests
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "manifests/deployment.yaml"
          propertyPath: "spec.template.spec.containers[0].image"
          value: ${{ env.DOCKER_IMAGE }}
          commitChange: true
          updateFile: true

      # TODO: Use kubeconfig from doctl
      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f manifests
